FROM nvidia/opengl:1.0-glvnd-runtime-ubuntu18.04

ENV DEBIAN_FRONTEND=noninteractive

COPY installers /tmp/installers
COPY rcfiles /tmp/rcfiles
COPY archive /tmp/archive

RUN bash /tmp/installers/common/config_env.sh

RUN bash /tmp/installers/3rdparties_slam/install_3rdparties_dev.sh

RUN rm -rf /tmp/installers && rm -rf /tmp/rcfiles && rm -rf /tmp/archive
