FROM nvidia/opengl:1.0-glvnd-runtime-ubuntu16.04 as glvnd_runtime

FROM ros:kinetic

ENV DEBIAN_FRONTEND=noninteractive

COPY --from=glvnd_runtime \
  /usr/local/lib/x86_64-linux-gnu \
  /usr/local/lib/x86_64-linux-gnu

COPY --from=glvnd_runtime \
  /usr/local/share/glvnd/egl_vendor.d/10_nvidia.json \
  /usr/local/share/glvnd/egl_vendor.d/10_nvidia.json

RUN echo '/usr/local/lib/x86_64-linux-gnu' >> /etc/ld.so.conf.d/glvnd.conf && \
  ldconfig && \
  echo '/usr/local/$LIB/libGL.so.1' >> /etc/ld.so.preload && \
  echo '/usr/local/$LIB/libEGL.so.1' >> /etc/ld.so.preload

ENV LD_LIBRARY_PATH /usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

ENV NVIDIA_VISIBLE_DEVICES \
  ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
  ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

COPY installers /tmp/installers
COPY rcfiles /tmp/rcfiles
COPY archive /tmp/archive

RUN bash /tmp/installers/common/config_env.sh

RUN bash /tmp/installers/3rdparties_slam/dev.sh

RUN rm -rf /tmp/installers && rm -rf /tmp/rcfiles && rm -rf /tmp/archive