name: Docker Image CI faster-lio

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image - faster-lio
      run: ./build.sh ./dockerfiles/Dockerfile.faster-lio
